### ISSUE TITLE
Does it work for Django 1.11 and Python 3.6

### ISSUE THREAD

**Issue by zheldRnaskan** [django-ses/django-ses#142] opened 2017-12-26 11:28 UTC
I've got an error "ImportError: Module "django_ses" does not define a "SESBackend" attribute/class" when I try to send a email using this library. I hope to use this one.

**Comment by pcraciunoiu** [comment] 2018-01-03 16:30
Duplicate of #142.

**Closed by pcraciunoiu** 2018-01-03 16:30 UTC
