### ISSUE TITLE
Caching of the SES rate limit is broken when using an IAM role

### ISSUE THREAD

**Issue by adarnimrod** [django-ses/django-ses#296] opened 2023-08-10 20:20 UTC
Hi,

We changed from using an IAM user (with an access key) to an IAM role recently and we started getting errors about the `GetSendQuota` API calls being throttled. Upon further inspection, I believe it is because that `get_rate_limit` uses the `_aws_access_key_id` as the cache key which we don't have since we're using an IAM role. Without the cached response, `get_rate_limit` fetches the SES rate limit using `GetSendQuota` each time an email is sent which ends up being throttled. Maybe in cases where the access key is not provided it would be possible to use the credentials from `get_credentials()` in the Boto3 session?

## Steps to reproduce

1. Use an AWS resource with an IAM role attached (like an EC2 instance or an ECS task).
2. Send multiple emails.
3. Check the usage with the metrics in CloudWatch (the sum of the `CallCount` metric for the `GetSendQuota` resource in the `SES` service in the `Usage` namesapce). You should see the call count matching the number of messages sent.

**Comment by pcraciunoiu** [comment] 2023-08-13 16:02
@adarnimrod thanks for reporting this issue. Would you be willing to open a pull request with a proposed fix? (and ideally unit test)

**Comment by mdw123** [comment] 2024-01-12 23:40
Same issue. Will look into a PR for this. Until then, enjoy this meme. :)
![image](https://github.com/django-ses/django-ses/assets/107448/71586868-92b8-4e7b-9ba4-f9f38adb3089)

**Comment by mdw123** [comment] 2024-01-13 00:45
Reading the code, I don't think this is an actual problem. There's probably a different reason you're calling get_send_quota too much.

cached_rate_limits is a dictionary.

If you use a machine role to access AWS, you correctly point out that self._access_key_id is unset. More specifically, self._access_key_id defaults to None based on line 9 of settings.py

```python
ACCESS_KEY = getattr(settings, 'AWS_SES_ACCESS_KEY_ID',
                     getattr(settings, 'AWS_ACCESS_KEY_ID', None))
```

Because (None or None) is None, the cache key is None. None is a valid index in a dictionary. Because you're using a machine role to access AWS, there is only ever one SES instance involved and because the cache key is None, I believe this code is functioning as designed, and this issue can be closed.

The problem is more likely because you have too many instances of django-ses trying to find out how to throttle their send rate at the same time, perhaps too many processes, too many nodes, too many somethings. But, within the context of that single EC2 instance, I think it is successfully using the cache.

I think I've figured out what *my* problem is in general, but I'm not sure how to fix it yet, so you can remove my +1 from this issue.

I think the code is working sufficiently well that you can close this issue.

**Closed** 2024-01-13 05:00 UTC
